Nao-setada: "&cA warp &f{warp} &cnão teve a localização definida."
Sem-permissao: "&cÉ necessário a permissão &f{permission} &cpara ir a esta warp."
Cancelar-mover: "%leaf_prefix% &fUtilize o comando novamente estando imóvel para ser redirecionado(a)."
Nao-poder-mover: "%leaf_prefix% &fAguarde &c{timer} &fsem se mexer para ser redirecionado(a)."
Mover-cancelar: "%leaf_prefix% &fO teletransporte foi cancelado."
Apenas-inventario-vazio: "%leaf_prefix% &fÉ necessário estar com o inventário vazio."
Apenas-inventario-com-item: "%leaf_prefix% &fÉ necessário estar com os itens requisitados."
Warp-definida: "%leaf_prefix% &fLocalização definida para &a{warp}&f!"
Warp-removida: "%leaf_prefix% &fWarp &c{warp} &fremovida!"
Warp-nao-encontrada: "%leaf_prefix% &fWarp &c{warp} &fnão encontrada!"
Warp-lista: "%leaf_prefix% &fLista de warps: {warps}"
